name: skip-firebase
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 7,22 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-framework.yml@v1
    with:
      # Firebase now requires Xcode 16, so it cannot run on macos-13
      # https://github.com/firebase/firebase-ios-sdk/issues/14732
      runs-on: "['macos-15']"
